<?php
/**
 * Created by PhpStorm.
 * User: himanshukotnala
 * Date: 2020-01-18
 * Time: 15:52
 */

namespace TDD\Test;
require_once dirname(dirname(__FILE__)). DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';
use PHPUnit\Framework\TestCase;
use TDD\Receipt;

class ReceiptTest extends TestCase
{
    protected $_receipt = null;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->_receipt = new Receipt();
    }

    public function testTotal(){
        $input = [2,3,5,2];
        $output = $this->_receipt->total($input);
        $this->assertEquals(
            12,
            $output,
            'The total should be 12 here!'
        );
    }

    public function testTax(){
        $total = 100;
        $taxPerc = .1;
        $output = $this->_receipt->calculateTax($taxPerc, $total);
        $this->assertEquals(
            10,
            $output,
            'Expected Tax value here is 10'
        );
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        unset($this->_receipt);
    }
}